[package]
name = "woko"
version = "0.1.0"
authors = ["Meno Abels <meno.abels@adviser.com>"]

[dependencies]
iron = "0.3.0"
time = "0.1.35"
regex = "0.1.69"
log = "0.3.6"
bodyparser = "0.3.0"
persistent = "0.1.0"
rustc-serialize = "0.3.19"
serde = "*"
serde_json = "*"
serde_macros = "*"

